---
- hosts: database
  become: true
  roles:
    - role: mysql
      mysql_db_name: "{{ demo_db_name }}"
      mysql_user_name: "{{ demo_db_user }}"
      mysql_user_pass: "{{ demo_db_pass }}"
      mysql_user_host: '%'
