---
- name: install tools
  apt: name="{{item}}" state=present
  with_items:
    - python-mysqldb
  tags: [ 'packages' ]

- name: install mysql-server
  apt: name=mysql-server state=present
  tags: [ 'packages' ]

- name: "ensure mysql listening on all ports"
  lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp=^bind-address
              line="bind-address = {{ ansible_ens160.ipv4.address }}"
  notify: "restart mysql"
  tags: [ 'configure' ]

- name: "ensure mysql started"
  service: name=mysql state=started enabled=yes
  tags: [ 'service' ]

- name: "create database"
  mysql_db: name={{ mysql_db_name }} state=present
  tags: [ 'configure' ]

- name: "create user"
  mysql_user: name={{ mysql_user_name }} password={{ mysql_user_pass }} priv={{ mysql_db_name }}.*:ALL
              host='{{ mysql_user_host }}' state=present
  tags: [ 'configure' ]
